_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "./output/coco_gray/train/model_reset_remove.pth"
  MASK_ON: False
  BACKBONE:
    FREEZE: False
    # FREEZE_AT: 5
  RESNETS:
    DEPTH: 101
  ENABLE_GLMD: True
  GLMD:
    ENABLE_CM: True
    ENABLE_LR: True
    ENABLE_MDF: True
    ENABLE_CRD: True
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
    # POST_NMS_TOPK_TRAIN: 4000
    FREEZE: False
    BBOX_OBJ_LOSS_TYPE: "CA"
  ROI_HEADS:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.01
    NUM_CLASSES: 11
    # BATCH_SIZE_PER_IMAGE: 256
    FREEZE_FEAT: True
    CLS_DROPOUT: True
    # OUTPUT_LAYER: "CosineSimOutputLayers"
  ROI_BOX_HEAD:
    BBOX_CLS_LOSS_TYPE: "CA"
  PIXEL_MEAN: [93.5781, 93.5781, 93.5781]  # ifsod
DATASETS:
  TRAIN: ('ifsod_finetune_novel_10shot',)
  TEST: ('ifsod_test_novel',)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  STEPS: (3000,)
  MAX_ITER: 4000
  CHECKPOINT_PERIOD: 500
  WARMUP_ITERS: 100
TEST:
  PCB_ENABLE: True
  PCB_MODELPATH: "/home/nvidia/xuyunkai/Model/resnet101-5d3b4d8f.pth"
  EVAL_PERIOD: 500
OUTPUT_DIR: "./output/ifsod/finetune_debug/"